# Generated by Django 4.1 on 2022-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=20)),
                ('MotherName', models.CharField(max_length=20)),
                ('SonName', models.CharField(max_length=20)),
                ('Daughter_1_Name', models.CharField(max_length=20)),
                ('Daughter_2_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
