# Generated by Django 4.1 on 2022-08-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0003_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Village_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
