# Generated by Django 4.1 on 2022-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0004_family_village_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Company', models.CharField(max_length=20)),
                ('Cream_Base', models.CharField(max_length=20)),
                ('Scrub_Base', models.CharField(max_length=20)),
                ('Lotion_Base', models.CharField(max_length=20)),
                ('Oil_Base', models.CharField(max_length=20)),
                ('Gel_Base', models.CharField(max_length=20)),
                ('Soap_Base', models.CharField(max_length=20)),
            ],
        ),
    ]
