# Generated by Django 4.1 on 2022-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0005_product_detailes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=20)),
                ('Employee_Salary', models.IntegerField()),
            ],
        ),
    ]
