# Generated by Django 4.1 on 2022-09-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0006_employee2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee2',
            new_name='Employee',
        ),
    ]
