# Generated by Django 4.1 on 2022-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0007_rename_employee2_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
