# Generated by Django 4.1 on 2022-09-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBoperations', '0010_alter_employee_dept_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['Employee_Salary']},
        ),
    ]
