# Generated by Django 4.1 on 2022-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
