# Generated by Django 4.1 on 2022-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_employee_empaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(null=True)),
                ('empaddress', models.TextField(max_length=100)),
                ('tiffin_menu', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
