# Generated by Django 4.1 on 2022-09-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(null=True)),
                ('empname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('tcs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='revision.tcs')),
                ('routes', models.CharField(max_length=20)),
            ],
            bases=('revision.tcs',),
        ),
    ]
