# Generated by Django 4.1 on 2022-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_tcs_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('prodId', models.IntegerField(primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=20)),
                ('prodimage', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('proddesc', models.TextField(max_length=50, null=True)),
                ('prodprice', models.IntegerField(null=True)),
            ],
        ),
    ]
