# Generated by Django 4.1 on 2022-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_detailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodId', models.IntegerField(null=True)),
                ('prodname', models.CharField(max_length=20)),
                ('proddesc', models.TextField(max_length=100)),
                ('prodprice', models.IntegerField()),
                ('prodimage', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='proddesc',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
