# Generated by Django 4.1 on 2022-09-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0006_product_detailes_alter_products_proddesc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detailes',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_detailes',
            name='prodId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_detailes',
            name='proddesc',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
