# Generated by Django 4.1 on 2022-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0007_remove_product_detailes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detailes',
            name='prodimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodimage',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\DjangoFolder\\myprojects\\media'),
        ),
    ]
