# Generated by Django 4.1 on 2022-09-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0008_alter_product_detailes_prodimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_detailes',
            options={'verbose_name_plural': 'product_detailes'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
    ]
