# Generated by Django 4.1 on 2022-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0009_alter_product_detailes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
