# Generated by Django 4.1 on 2022-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0010_alter_products_prodimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=20)),
                ('StudentAge', models.IntegerField(max_length=10)),
                ('StudentAddress', models.CharField(max_length=20)),
            ],
        ),
    ]
