# Generated by Django 4.1 on 2022-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0011_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentAge',
            field=models.IntegerField(),
        ),
    ]
