# Generated by Django 4.1 on 2022-09-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dairy',
            new_name='Diary',
        ),
    ]
