# Generated by Django 4.1 on 2022-09-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealProject', '0003_loginpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginpage',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='loginpage',
            old_name='username',
            new_name='Username',
        ),
    ]
