# Generated by Django 4.1 on 2022-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealProject', '0004_rename_password_loginpage_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='Username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
