# Generated by Django 4.1 on 2022-09-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealProject', '0006_mainpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Signuppage',
        ),
    ]
