# Generated by Django 4.1 on 2022-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeinfo',
            fields=[
                ('EmployeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=20)),
                ('EmployeeSalary', models.IntegerField()),
                ('Employeeaddress', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
    ]
