# Generated by Django 4.1 on 2022-09-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0002_employeeinfo_alter_family_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='Employeeaddress',
        ),
    ]
