# Generated by Django 4.1 on 2022-09-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0003_remove_employeeinfo_employeeaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='EmployeeId',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='EmployeeName',
            new_name='employeename',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='EmployeeSalary',
            new_name='employeesalary',
        ),
    ]
