# Generated by Django 4.1 on 2022-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0004_rename_employeeid_employeeinfo_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='empaddress',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
