# Generated by Django 4.1 on 2022-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazonproducts',
            fields=[
                ('prodId', models.IntegerField(primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=10)),
                ('prodimage', models.ImageField(upload_to='media/')),
                ('prodprice', models.IntegerField()),
            ],
        ),
    ]
