# Generated by Django 4.1 on 2022-09-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproducts',
            name='prodimage',
        ),
    ]
