# Generated by Django 4.1 on 2022-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_remove_amazonproducts_prodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproducts',
            name='prodname',
            field=models.CharField(max_length=20),
        ),
    ]
