# Generated by Django 4.1 on 2022-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_alter_amazonproducts_prodname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonproducts',
            options={'verbose_name_plural': 'Amazonproducts'},
        ),
        migrations.AddField(
            model_name='amazonproducts',
            name='prodimage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
